# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a15tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/TI LAB/Desktop/2WMIPS32/2WSSP/2WSSP.cache/wt} [current_project]
set_property parent.project_path {C:/Users/TI LAB/Desktop/2WMIPS32/2WSSP/2WSSP.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {c:/Users/TI LAB/Desktop/2WMIPS32/2WSSP/2WSSP.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/TI LAB/Desktop/2WMIPS32/2WSSP/2WSSP.srcs/sources_1/new/2WSsP3InputMux.vhd}
  {C:/Users/TI LAB/Desktop/2WMIPS32/2WSSP/2WSSP.srcs/sources_1/new/2WSsPControlUnit.vhd}
  {C:/Users/TI LAB/Desktop/2WMIPS32/2WSSP/2WSSP.srcs/sources_1/new/2WSsPDmem.vhd}
  {C:/Users/TI LAB/Desktop/2WMIPS32/2WSSP/2WSSP.srcs/sources_1/new/2WSsPHazardUnit.vhd}
  {C:/Users/TI LAB/Desktop/2WMIPS32/2WSSP/2WSSP.srcs/sources_1/new/2WSsP_2InputMux_32.vhd}
  {C:/Users/TI LAB/Desktop/2WMIPS32/2WSSP/2WSSP.srcs/sources_1/new/2WSsPregFile.vhd}
  {C:/Users/TI LAB/Desktop/2WMIPS32/2WSSP/2WSSP.srcs/sources_1/new/2WSspImem.vhd}
  {C:/Users/TI LAB/Desktop/2WMIPS32/2WSSP/2WSSP.srcs/sources_1/new/2WSspInstrScheduler.vhd}
  {C:/Users/TI LAB/Desktop/2WMIPS32/2WSSP/2WSSP.srcs/sources_1/new/2WSspProgramCounter.vhd}
  {C:/Users/TI LAB/Desktop/2WMIPS32/2WSSP/2WSSP.srcs/sources_1/imports/new/32BitsignExtender.vhd}
  {C:/Users/TI LAB/Desktop/2WMIPS32/2WSSP/2WSSP.srcs/sources_1/imports/new/7inputMux.vhd}
  {C:/Users/TI LAB/Desktop/2WMIPS32/2WSSP/2WSSP.srcs/sources_1/imports/new/ALU.vhd}
  {C:/Users/TI LAB/Desktop/2WMIPS32/2WSSP/2WSSP.srcs/sources_1/imports/PP_BoardImplementation/ALUdecoder.vhd}
  {C:/Users/TI LAB/Desktop/2WMIPS32/2WSSP/2WSSP.srcs/sources_1/imports/new/CLA32Adder.vhd}
  {C:/Users/TI LAB/Desktop/2WMIPS32/2WSSP/2WSSP.srcs/sources_1/imports/PP_BoardImplementation/ControlUnit.vhd}
  {C:/Users/TI LAB/Desktop/2WMIPS32/2WSSP/2WSSP.srcs/sources_1/new/DEpipelineReg.vhd}
  {C:/Users/TI LAB/Desktop/2WMIPS32/2WSSP/2WSSP.srcs/sources_1/new/Datapath.vhd}
  {C:/Users/TI LAB/Desktop/2WMIPS32/2WSSP/2WSSP.srcs/sources_1/new/EMpipelineReg.vhd}
  {C:/Users/TI LAB/Desktop/2WMIPS32/2WSSP/2WSSP.srcs/sources_1/new/FDpipelineReg.vhd}
  {C:/Users/TI LAB/Desktop/2WMIPS32/2WSSP/2WSSP.srcs/sources_1/new/HU1_interpath.vhd}
  {C:/Users/TI LAB/Desktop/2WMIPS32/2WSSP/2WSSP.srcs/sources_1/new/HU2.vhd}
  {C:/Users/TI LAB/Desktop/2WMIPS32/2WSSP/2WSSP.srcs/sources_1/new/HU_interpath.vhd}
  {C:/Users/TI LAB/Desktop/2WMIPS32/2WSSP/2WSSP.srcs/sources_1/new/MWBpipelineReg.vhd}
  {C:/Users/TI LAB/Desktop/2WMIPS32/2WSSP/2WSSP.srcs/sources_1/new/PCMUX.vhd}
  {C:/Users/TI LAB/Desktop/2WMIPS32/2WSSP/2WSSP.srcs/sources_1/imports/new/andGate.vhd}
  {C:/Users/TI LAB/Desktop/2WMIPS32/2WSSP/2WSSP.srcs/sources_1/imports/PP_BoardImplementation/hazardDetectionUnit.vhd}
  {C:/Users/TI LAB/Desktop/2WMIPS32/2WSSP/2WSSP.srcs/sources_1/imports/PP_BoardImplementation/mainDecoder.vhd}
  {C:/Users/TI LAB/Desktop/2WMIPS32/2WSSP/2WSSP.srcs/sources_1/new/newComp.vhd}
  {C:/Users/TI LAB/Desktop/2WMIPS32/2WSSP/2WSSP.srcs/sources_1/imports/new/notGate.vhd}
  {C:/Users/TI LAB/Desktop/2WMIPS32/2WSSP/2WSSP.srcs/sources_1/imports/new/orGate.vhd}
  {C:/Users/TI LAB/Desktop/2WMIPS32/2WSSP/2WSSP.srcs/sources_1/imports/new/shiftLeft2.vhd}
  {C:/Users/TI LAB/Desktop/2WMIPS32/2WSSP/2WSSP.srcs/sources_1/new/twoWaySsProcessor.vhd}
  {C:/Users/TI LAB/Desktop/2WMIPS32/2WSSP/2WSSP.srcs/sources_1/imports/new/xorGate.vhd}
}
read_vhdl -vhdl2008 -library xil_defaultlib {
  {C:/Users/TI LAB/Desktop/2WMIPS32/2WSSP/2WSSP.srcs/sources_1/imports/new/sllGate.vhd}
  {C:/Users/TI LAB/Desktop/2WMIPS32/2WSSP/2WSSP.srcs/sources_1/imports/new/srlGate.vhd}
  {C:/Users/TI LAB/Desktop/2WMIPS32/2WSSP/2WSSP.srcs/sources_1/new/TopLevelModule.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top TopLevelModule -part xc7a15tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef TopLevelModule.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file TopLevelModule_utilization_synth.rpt -pb TopLevelModule_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
